### PR TITLE
Fix encoding of cloudinary URLs

### PR DESCRIPTION
**Pull request by sedubois**

### CODE REVIEW

**Comment by sedubois** [comment]
Fixes https://github.com/OpenCollective/OpenCollective/issues/41

**Comment by sedubois** [comment]
Merging this because needs to be on master to avoid the npm install cyclic dep

**Comment by asood123** [comment]
We'll also need to update the other thankyou templates.

**Comment by sedubois** [comment]
Good point... https://github.com/OpenCollective/api/pull/294

**Pull request merged**
